name: Deploy Stats Lambda

on:
  push:
    branches:
      - "aws-deploy"
    paths:
      - "src/stats_lambda/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Zip File
        run: |
          cd src/stats_lambda
          zip function_stats.zip lambda_function.py
      - name: Deploy
        uses: kazimanzurrashid/aws-lambda-update-action@v1
        with:
          zip-file: src/stats_lambda/function_stats.zip
          publish: true
          lambda-name: stats
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
